apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: mlflow-ingress
  namespace: mlflow
  annotations:
    # indica al operador ngrok qu√© puerto del Service corresponde a HTTPS/HTTP
    k8s.ngrok.com/app-protocols: '{"https":"https","http":"http"}'
spec:
  ingressClassName: ngrok
  rules:
    - host: refined-antelope-typically.ngrok-free.app
      http:
        paths:
          - path: /mlflow
            pathType: Prefix
            backend:
              service:
                name: mlflow-server-service
                port:
                  number: 5000