mlflow-server:
  s3:
    endpointUrl: http://mlflow-minio.mlflow:9000
    accessKeyId: admin 
    secretAccessKey: andresRules
    bucket: mlflow
minio:
  console:
    image:
      registry: docker.io
      repository: bitnamilegacy/minio-object-browser
      tag: 2.0.2-debian-12-r3
      digest: ""
  image:
    registry: docker.io
    repository: bitnamilegacy/minio
    tag: 2025.7.23-debian-12-r3
  tls:
    enabled: false
  auth:
    ## @param auth.rootUser MinIO&reg; root username
    ##
    # rootUser: andres
    ## @param auth.rootPassword Password for MinIO&reg; root user
    ##
    rootPassword: "andresRules"
  defaultBuckets: "mlflow"
postgresql-ha:
  postgresql:
    image:
    registry: docker.io
    repository: bitnamilegacy/postgresql-repmgr
    tag: 14.7.0-debian-11-r17